pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }

    }
    stages {
        stage('Build') {
            steps {
                dir ("simple-java-maven-app") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir ("simple-java-maven-app") {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir ("simple-java-maven-app") {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
